name: FlashSimMinimal
channels:
  - conda-forge
dependencies:
  - python
  - numpy>=1.18.1
  - pandas
  - root
  - uproot
  - mplhep
  - coffea
  - pip:
      - absl-py==1.4.0
      - cachetools==5.3.0
      - future==0.18.2
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - h5py==3.8.0
      - markdown==3.4.1
      - nflows==0.14
      - numexpr==2.8.1
      - oauthlib==3.2.2
      - protobuf==3.20.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tables==3.7.0
      - tensorboard
      - tensorboard-data-server
      - tensorboard-plugin-wit
      - torch
      - torchvision
      - tqdm
      - werkzeug==2.2.2
